// Generated by CoffeeScript 1.7.1
(function() {
  var gutil, through;

  through = require("through2");

  gutil = require("gulp-util");

  module.exports = function(options) {
    var indent;
    if (options == null) {
      options = {};
    }
    if (options.tabs == null) {
      options.tabs = false;
    }
    if (options.amount == null) {
      options.amount = 2;
    }
    indent = function(file, enc, done) {
      var character, indentation, line, lines, number, _i, _ref;
      if (file.isNull()) {
        this.push(file);
        return done();
      }
      if (file.isStream()) {
        this.emit("error", new gutil.PluginError("gulp-indent", "Stream content is not supported"));
        return done();
      }
      if (file.isBuffer()) {
        character = options.tabs ? "\t" : " ";
        indentation = "";
        for (number = _i = 0, _ref = options.amount; 0 <= _ref ? _i < _ref : _i > _ref; number = 0 <= _ref ? ++_i : --_i) {
          indentation += character;
        }
        lines = file.contents.toString().split("\n");
        lines = (function() {
          var _j, _len, _results;
          _results = [];
          for (_j = 0, _len = lines.length; _j < _len; _j++) {
            line = lines[_j];
            _results.push(indentation + line);
          }
          return _results;
        })();
        file.contents = new Buffer(lines.join("\n"));
        this.push(file);
      }
      return done();
    };
    return through.obj(indent);
  };

}).call(this);
